### ISSUE TITLE
HTML & CSS - Structuring Our Page - Codepen template images reference localhost 

### ISSUE THREAD

**Issue by ollief87** [SheCodesAustralia/workshopcontent#30]
The images in the Codepen [HTML & CSS Workshop - Part 2 - Template](https://codepen.io/shecodesaus/pen/MWOOeoZ) referenced in [/content/html_and_css/4_structure/_index.md](https://github.com/SheCodesAustralia/workshopcontent/blob/main/content/html_and_css/4_structure/_index.md) point to localhost URL's:
![image](https://github.com/SheCodesAustralia/workshopcontent/assets/7812769/50f2371e-ab68-46fd-84cf-2675a349ceed)

**Comment by mandydc10** [comment]
Codepen HTML needs to be updated with: 
- img src="https://assets.codepen.io/5804361/turtle_1.jpg"
- img src="https://assets.codepen.io/5804361/turtle_2.jpg"
- img src="https://assets.codepen.io/5804361/turtle_3.jpg"

**Comment by katekirwin** [comment]
Resolved!
