### ISSUE TITLE
HTML & CSS: HTML Challenges, Challenge 2 - Use of Section element contradicts prior tutorial explanation

### ISSUE THREAD

**Issue by mandydc10** [SheCodesAustralia/workshopcontent#41]
CONTEXT - HTML & CSS > Structuring our page > Sections
The first paragraph on this page describes the important defining characteristic of a section with the following instruction, "a section always has a heading element", which is what differentiates this element from a div element, screenshot below.
<img width="858" alt="HTML   CSS Sections tutorial" src="https://github.com/user-attachments/assets/66f94119-2988-4a50-969a-27c7b86628af">

ISSUE - HTML & CSS > HTML Challenges > Challenge 2 
This challenge asks for 2x section elements to be added. To get the page looking identical to the tutorial reference image, the second section element needs to wrap around the three example jokes (code lines 8-10 in screenshot below), however this part of the HTML has no heading element.
<img width="1063" alt="Screenshot 2024-10-30 at 4 33 10 pm" src="https://github.com/user-attachments/assets/43eb6795-a363-4e1e-a63a-cc9229a12f18">

SUGGESTED FIX
- Add heading element to codepen HTML (after code line 7) eg. screenshot below (shown as line 18 in this screenshot as challenge has been completed to validate suggested fix). 
- Update tutorial reference image to reflect changes in HTML code.

<img width="1232" alt="Codepen suggested HTML change" src="https://github.com/user-attachments/assets/509d0c45-3ce9-4378-b743-50ec1a88ef96">

**Comment by katekirwin** [comment]
Ok so for this one I think I've fixed it in the code but can't work out how to update the screenshot in the tutorial...

**Comment by KayeDante89** [comment]
@katekirwin Hi Kate, I added a PR with the updated screenshot
